export type Key = {
	valueRUS: string
	valueENG: string
	valueNUM_RUS: string
	valueNUM_ENG: string
	class: string
	icon?: string
	size?: string
	cut?: boolean
	noEffect?: true
}

export const keys: Key[] = [
	{
		valueRUS: 'й',
		valueENG: 'q',
		valueNUM_RUS: '1',
		valueNUM_ENG: '1',
		class: 'key',
	},
	{
		valueRUS: 'ц',
		valueENG: 'w',
		valueNUM_RUS: '2',
		valueNUM_ENG: '2',
		class: 'key',
	},
	{
		valueRUS: 'у',
		valueENG: 'e',
		valueNUM_RUS: '3',
		valueNUM_ENG: '3',
		class: 'key',
	},
	{
		valueRUS: 'к',
		valueENG: 'r',
		valueNUM_RUS: '4',
		valueNUM_ENG: '4',
		class: 'key',
	},
	{
		valueRUS: 'е',
		valueENG: 't',
		valueNUM_RUS: '5',
		valueNUM_ENG: '5',
		class: 'key',
	},
	{
		valueRUS: 'н',
		valueENG: 'y',
		valueNUM_RUS: '6',
		valueNUM_ENG: '6',
		class: 'key',
	},
	{
		valueRUS: 'г',
		valueENG: 'u',
		valueNUM_RUS: '7',
		valueNUM_ENG: '7',
		class: 'key',
	},
	{
		valueRUS: 'ш',
		valueENG: 'i',
		valueNUM_RUS: '8',
		valueNUM_ENG: '8',
		class: 'key',
	},
	{
		valueRUS: 'щ',
		valueENG: 'o',
		valueNUM_RUS: '9',
		valueNUM_ENG: '9',
		class: 'key',
	},
	{
		valueRUS: 'з',
		valueENG: 'p',
		valueNUM_RUS: '0',
		valueNUM_ENG: '0',
		class: 'key',
	},
	{
		valueRUS: 'х',
		valueENG: '[',
		valueNUM_RUS: '-',
		valueNUM_ENG: '-',
		class: 'key',
	},
	{
		valueRUS: 'ъ',
		valueENG: ']',
		valueNUM_RUS: '=',
		valueNUM_ENG: '=',
		class: 'key',
	},
	{
		valueRUS: 'backspace',
		valueENG: 'backspace',
		valueNUM_RUS: 'backspace',
		valueNUM_ENG: 'backspace',
		class: 'key key-192',
		icon: 'backspace',
		size: '60',
	},
	{
		valueRUS: 'shift',
		valueENG: 'shift',
		valueNUM_RUS: 'shift',
		valueNUM_ENG: 'shift',
		class: 'key key-144',
		icon: 'shift',
		size: '48',
	},
	{
		valueRUS: 'ф',
		valueENG: 'a',
		valueNUM_RUS: '!',
		valueNUM_ENG: '!',
		class: 'key',
	},
	{
		valueRUS: 'ы',
		valueENG: 's',
		valueNUM_RUS: '@',
		valueNUM_ENG: '@',
		class: 'key',
	},
	{
		valueRUS: 'в',
		valueENG: 'd',
		valueNUM_RUS: '#',
		valueNUM_ENG: '#',
		class: 'key',
	},
	{
		valueRUS: 'а',
		valueENG: 'f',
		valueNUM_RUS: '$',
		valueNUM_ENG: '$',
		class: 'key',
	},
	{
		valueRUS: 'п',
		valueENG: 'g',
		valueNUM_RUS: '%',
		valueNUM_ENG: '%',
		class: 'key',
	},
	{
		valueRUS: 'р',
		valueENG: 'h',
		valueNUM_RUS: '^',
		valueNUM_ENG: '^',
		class: 'key',
	},
	{
		valueRUS: 'о',
		valueENG: 'j',
		valueNUM_RUS: '&',
		valueNUM_ENG: '&',
		class: 'key',
	},
	{
		valueRUS: 'л',
		valueENG: 'k',
		valueNUM_RUS: '*',
		valueNUM_ENG: '*',
		class: 'key',
	},
	{
		valueRUS: 'д',
		valueENG: 'l',
		valueNUM_RUS: '(',
		valueNUM_ENG: '(',
		class: 'key',
	},
	{
		valueRUS: 'ж',
		valueENG: ';',
		valueNUM_RUS: ')',
		valueNUM_ENG: ')',
		class: 'key',
	},
	{
		valueRUS: 'э',
		valueENG: '"',
		valueNUM_RUS: '_',
		valueNUM_ENG: '_',
		class: 'key',
	},
	{
		valueRUS: 'Enter',
		valueENG: 'Enter',
		valueNUM_RUS: 'Enter',
		valueNUM_ENG: 'Enter',
		class: 'key key-192',
		noEffect: true,
	},
	{
		cut: true,
		valueRUS: '&123_RUS',
		valueENG: '&123_ENG',
		valueNUM_RUS: 'АБВ____',
		valueNUM_ENG: 'ABC____',
		class: 'key key-192',
		noEffect: true,
	},
	{
		valueRUS: 'я',
		valueENG: 'z',
		valueNUM_RUS: '+',
		valueNUM_ENG: '+',
		class: 'key',
	},
	{
		valueRUS: 'ч',
		valueENG: 'x',
		valueNUM_RUS: '{',
		valueNUM_ENG: '{',
		class: 'key',
	},
	{
		valueRUS: 'с',
		valueENG: 'c',
		valueNUM_RUS: '}',
		valueNUM_ENG: '}',
		class: 'key',
	},
	{
		valueRUS: 'м',
		valueENG: 'v',
		valueNUM_RUS: ':',
		valueNUM_ENG: ':',
		class: 'key',
	},
	{
		valueRUS: 'и',
		valueENG: 'b',
		valueNUM_RUS: '"',
		valueNUM_ENG: '"',
		class: 'key',
	},
	{
		valueRUS: 'т',
		valueENG: 'n',
		valueNUM_RUS: '|',
		valueNUM_ENG: '|',
		class: 'key',
	},
	{
		valueRUS: 'ь',
		valueENG: 'm',
		valueNUM_RUS: '<',
		valueNUM_ENG: '<',
		class: 'key',
	},
	{
		valueRUS: 'б',
		valueENG: ',',
		valueNUM_RUS: '>',
		valueNUM_ENG: '>',
		class: 'key',
	},
	{
		valueRUS: 'ю',
		valueENG: '.',
		valueNUM_RUS: '.',
		valueNUM_ENG: '.',
		class: 'key',
	},
	{
		valueRUS: '.',
		valueENG: '/',
		valueNUM_RUS: '/',
		valueNUM_ENG: '/',
		class: 'key',
	},
	{
		cut: true,
		valueRUS: 'ENG____',
		valueENG: 'RUS____',
		valueNUM_RUS: 'ENG_NUM',
		valueNUM_ENG: 'RUS_NUM',
		class: 'key key-192',
		noEffect: true,
	},
	{
		valueRUS: ' ',
		valueENG: ' ',
		valueNUM_RUS: ' ',
		valueNUM_ENG: ' ',
		class: 'key key-1024',
	},
]
